// Copyright (c) 2020 Davide Gironi
// Please refer to LICENSE file for licensing information.

// load settings
import Config from '../config/config';

/**
 * themers
 */
const themes = {
  // default theme
  default: {
    COLOR_BACKGROUNDCOLOR: '#ffffff',
    COLOR_NAVIGATOR_BACKGROUNDCOLOR: '#373D40',
    COLOR_NAVIGATOR_HEADERTINTCOLOR: '#ffffff',
    COLOR_BUTTONADD_BACKGROUNDCOLOR: '#79868C',
    COLOR_TEXTINPUT_COLOR: '#000000',
    COLOR_TEXTINPUT_DISABLEDCOLOR: '#000000',
    COLOR_TEXTINPUT_DISABLEDBACKGROUNDCOLOR: '#D1CEC8',
    COLOR_BUTTONADD_COLOR: '#ffffff',
    COLOR_BUTTONSAVE_BACKGROUNDCOLOR: '#79868C',
    COLOR_BUTTONSAVE_COLOR: '#ffffff',
    COLOR_BUTTONINROW_COLOR: '#6B818C',
    COLOR_BUTTONINROW_BACKGROUNDCOLOR: 'transparent',
    COLOR_ROW_BACKGROUNDCOLOR: '#ffffff',
    COLOR_ROWACTIONS_BACKGROUNDCOLOR: '#ffffff',
    COLOR_FLATLIST_SEPARATORCOLOR: 'transparent',
    COLOR_SORT_COLOR: '#AFC2CC',
    COLOR_TOOLS_BORDERCOLOR: '#79868C',
    COLOR_TOOLSDICE_COLOR: '#91AAFF',
    COLOR_TOOLSCOUNTDOWNTIMER_COLOR: '#BD9EFF',
    COLOR_SORT_SELECTEDCOLOR: '#373D40',
    COLOR_BUTTONPOINTS_COLOR: '#6B818C',
    COLOR_SPLASHBACKGROUNDCOLOR: '#373D40',
    COLOR_SPLASHCOLOR: '#ffffff',
    COLOR_TEXTINPUT_BACKGROUNDCOLOR: '#AFC2CC',
    COLOR_SWITCH_THUMBCOLORON: '#ffffff',
    COLOR_SWITCH_THUMBCOLOROFF: '#ffffff',
    COLOR_SWITCH_TRACKCOLORON: '#AFC2CC',
    COLOR_SWITCH_TRACKCOLOROFF: '#8C846B',
    COLOR_PLAYER_WINNERIMAGECOLOR: '#4C59A6',
    COLOR_PLAYER_IMAGECOLOR: '#8C846B',
    COLOR_SETTINGS_HEADERBACKGROUNDCOLOR: '#79868C',
    COLOR_SETTINGS_HEADERCOLOR: '#ffffff',
    COLOR_SETTINGS_ITEMBACKGROUNDCOLOR: '#ffffff',
    COLOR_SETTINGS_ITEMCOLOR: '#000000',
    COLOR_SETTINGS_SWITCHTHUMBCOLORON: '#ffffff',
    COLOR_SETTINGS_SWITCHTHUMBCOLOROFF: '#ffffff',
    COLOR_SETTINGS_SWITCHTRACKCOLORON: '#AFC2CC',
    COLOR_SETTINGS_SWITCHTRACKCOLOROFF: '#8C846B',
    COLOR_BACKUPRESTORE_SEPARATORCOLOR: '#D1CEC8'
  }
};

/**
 * export the selected theme
 */
export default themes[Config.theme];
